// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANVsHoolb5F5NkRVJWDR7l3-4hiKhK8GA',
    appId: '1:396044178296:web:197d2ef881ebc7f4ec2e8d',
    messagingSenderId: '396044178296',
    projectId: 'maelect4-2961b',
    authDomain: 'maelect4-2961b.firebaseapp.com',
    databaseURL: 'https://maelect4-2961b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maelect4-2961b.appspot.com',
    measurementId: 'G-06HT0807J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU4PCseRDFsPOQ93C2kDQte2tiJ3ytHI0',
    appId: '1:396044178296:android:781b7feee889e375ec2e8d',
    messagingSenderId: '396044178296',
    projectId: 'maelect4-2961b',
    databaseURL: 'https://maelect4-2961b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maelect4-2961b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYbvo41BNKljVQdk0fdrAThCEJPAAGv6Q',
    appId: '1:396044178296:ios:a55a01b3b188bc64ec2e8d',
    messagingSenderId: '396044178296',
    projectId: 'maelect4-2961b',
    databaseURL: 'https://maelect4-2961b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maelect4-2961b.appspot.com',
    iosBundleId: 'com.example.mealsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYbvo41BNKljVQdk0fdrAThCEJPAAGv6Q',
    appId: '1:396044178296:ios:a55a01b3b188bc64ec2e8d',
    messagingSenderId: '396044178296',
    projectId: 'maelect4-2961b',
    databaseURL: 'https://maelect4-2961b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maelect4-2961b.appspot.com',
    iosBundleId: 'com.example.mealsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANVsHoolb5F5NkRVJWDR7l3-4hiKhK8GA',
    appId: '1:396044178296:web:91088bd98766fc40ec2e8d',
    messagingSenderId: '396044178296',
    projectId: 'maelect4-2961b',
    authDomain: 'maelect4-2961b.firebaseapp.com',
    databaseURL: 'https://maelect4-2961b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maelect4-2961b.appspot.com',
    measurementId: 'G-8TXHL7GJ71',
  );

}